### ISSUE TITLE
TCRT file size limit

### ISSUE THREAD

**Issue by dikdom** [ikorb/tapecart#3]
Hello,
I read in the TCRT file format doc that `[..] to 2097152 (0x200000) for the full flash memory. A TCRT file with a larger value in this field is invalid. [...]` . 
Is there any particular reason for that? 
I mean there are cheap W25Q chips (W25Q32/64/128) having 4/8/16MB capacity which easily fit into the DIY board. Their size can also be autodetected so the firmware doesn't really have to be aware of the size during compile time.
Is it only because the SMD variant can't have more than 2MB and you want to keep it compatible? Or?
I'm working on elevating this limit by modifying the firmware. If you're interested in the autodetect code it's already in my forked repo.

Thanks!

**Comment by ikorb** [comment]
The reason is compatibility: A conformant TCRT file will work with any existing TapeCart in the world, similar to EasyFlash cartridge images. Increasing this limit basically says "too bad, sucker" to anyone who bought a lower-capacity device, so I do not consider it acceptable to raise this limit.

Note that this does not preclude future devices that offers selectable TapeCart "banks" of 2MB each, similar to the EasyFlash 3.

**Comment by dikdom** [comment]
It's your project. But I would see this as  a natural evolution of the tapecart. Those, who have 2MB tapecart will have a v1.0 fw and v1.0 TCRT file support. Fw v2.0 and Tcrt v2.0 has an improved feature set (larger address space), that wouldn't mean that you failed your followers/customers.
Please don't get me wrong, this is a cool project as is right now, but I can think this would improve it.

Anyway, for myself I will enhance it this way, but I use a simple eeprom burner to write the content to the flash chip. To write 8MB (or 16MB) content to the flash would take a day from the C64.
